# Generated by Django 5.1.1 on 2024-09-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='name',
            new_name='label',
        ),
    ]
